- q2_feature_classifier/tests/__init__.py
> TST: Update import location of TestPluginBase

- q2_feature_classifier/_taxonomic_classifier.py
> REF: Pluralize type registration

- README.md
This adds a brief note to the readme pointing readers to the QIIME 2 wiki.
> MAINT: Update readme with link to wiki.

- q2_feature_classifier/_skl.py
This reverts commit e110e9c4310e77b1bb91ec6178c6a2412adec067.
> temporarily revert @BenKaehler's commit to prep master for release

- setup.py
_Do not merge, waiting on version release._
> MAINT: 0.0.6.dev

- q2_feature_classifier/_cutter.py
- q2_feature_classifier/_taxonomic_classifier.py
- q2_feature_classifier/tests/test_taxonomic_classifier.py
Pair-programmed with @thermokarst and @ebolyen.
> MISC: minor additions based on review of #47

- q2_feature_classifier/_blast.py
- q2_feature_classifier/_cutter.py
- q2_feature_classifier/_skl.py
- q2_feature_classifier/_vsearch.py
- q2_feature_classifier/classifier.py
- q2_feature_classifier/custom.py
- q2_feature_classifier/tests/test_classifier.py
- q2_feature_classifier/tests/test_consensus_assignment.py
- q2_feature_classifier/tests/test_custom.py
Fixes qiime2/q2-feature-classifier#59
Fixes qiime2/q2-feature-classifier#58
Fixes qiime2/q2-feature-classifier#57
Fixes qiime2/q2-feature-classifier#53
Addresses most of qiime2/q2-feature-classifier#54
> FIX: a variety of small enhancements and fixes

- q2_feature_classifier/_consensus_assignment.py
- q2_feature_classifier/tests/data/taxonomy.tsv
- q2_feature_classifier/tests/test_consensus_assignment.py
Related to changes introduced in https://github.com/qiime2/q2-types/pull/120.
> MAINT: Update test taxonomy data

- ci/recipe/meta.yaml
We'll revert this once we've retrained our classifiers.
> HACK: temporarily fix sklearn version

- q2_feature_classifier/_blast.py
> remove defunct threads param from blast

- ci/recipe/meta.yaml
This reverts commit 27a5891bb5d938055bb180056f95924f2804d107.
> Revert "HACK: temporarily fix sklearn version (#79)"

- q2_feature_classifier/tests/test_taxonomic_classifier.py
This reverts commit 4b7233b48e608a5944fa7e52d9bb33ed58ba7c43.
> Revert "MAINT: update tests to use _validate_ (#91)"

- ci/recipe/meta.yaml
Note to reviewer: please rebase and merge.
> Revert "MAINT: temporarily pin sklearn 0.19.0 (#94)"

- q2_feature_classifier/_skl.py
> naive bayes defaults set to "balanced"

- q2_feature_classifier/classifier.py
> masked out memory param

- ci/recipe/meta.yaml
See https://github.com/qiime2/q2-alignment/pull/56#issuecomment-422412144 - trying to resolve dependency hell.
> Allow blast 2.6.0 _and greater_

- q2_feature_classifier/_blast.py
- q2_feature_classifier/_vsearch.py
> better description of maxaccepts params

- q2_feature_classifier/_blast.py
- q2_feature_classifier/_vsearch.py
> fixed vsearch maxaccepts range

- q2_feature_classifier/_cutter.py
- q2_feature_classifier/tests/test_cutter.py
> extract-reads: added min/max length filtering parameters

- ci/recipe/meta.yaml
> BLD: pin scikit-learn at build time

- q2_feature_classifier/classifier.py
- q2_feature_classifier/tests/test_classifier.py
Brief summary of the Pull Request, including any issues it may fix using the GitHub closing syntax:
Closes #130.
Also, include any co-authors or contributors using the GitHub coauthor tag:
Co-authored-by: Nicholas Bokulich <nbokulich@users.noreply.github.com>
> ENH: capped reads per batch (#130)

- ci/recipe/meta.yaml
This probably won't work... but maybe it will.
> DIST: test dynamic pinning on build

- ci/recipe/meta.yaml
Reverts qiime2/q2-feature-classifier#137
It did not work.
> Revert "DIST: test dynamic pinning on build"

- ci/recipe/meta.yaml
If this doesn't work, I'm going home. If it does work, same situation.
> BUILD: pin scikit-learn 0.21.2

- ci/recipe/meta.yaml
> DEP: Unpin sklearn

- ci/recipe/meta.yaml
- q2_feature_classifier/_skl.py
- q2_feature_classifier/_taxonomic_classifier.py
- q2_feature_classifier/classifier.py
- q2_feature_classifier/tests/test_classifier.py
- q2_feature_classifier/tests/test_taxonomic_classifier.py
> MAINT: stop loading joblib through sklearn (#134)

- ci/recipe/meta.yaml
- q2_feature_classifier/_consensus_assignment.py
- q2_feature_classifier/_skl.py
- q2_feature_classifier/_vsearch.py
- q2_feature_classifier/classifier.py
- q2_feature_classifier/tests/test_consensus_assignment.py
This reverts commit df1756996ef240090d897d4fcc5013f4f8d82421.
> Revert "Revert hybrid classifier"

- q2_feature_classifier/_cutter.py
- q2_feature_classifier/tests/test_cutter.py
> FIX: Fix some issues with parallelizing extract_reads

- q2_feature_classifier/_skl.py
- q2_feature_classifier/classifier.py
This initial commit is provides a more clear `MemoryError` message. This PR is meant to resolve issue #131. 
OSX seems to bypass RAM, once memory has been exceeded, and will start to use storage space. I attempted to artificially lower the memory available for this process, but OSX disregards the use of `ulimit` commands. I could not recreate the issue on OSX because of this.
I was able to recreate the memory issue on Linux Ubuntu. There was no need to artificially limit memory using Linux. The terminal produces the `MemoryError` after allowing this process to consume available memory.
> ENH: Initial commit to improve the memory error

- q2_feature_classifier/_cutter.py
- q2_feature_classifier/custom.py
- q2_feature_classifier/tests/test_cutter.py
Solving issue trim_right qiime2/q2-feature-classifier#160
> issue #160 solved

- ci/recipe/meta.yaml
cross-reference: https://github.com/qiime2/docs/pull/470
fixes https://github.com/qiime2/q2-feature-classifier/issues/161
> DEP: unpin sklearn 0.22.1
